<?php


class Brands_Admin extends CoreA
{
    protected $db_info_brands;
    protected $approve_br;
    protected $delete_br;
    public function get_admin()
    {
        parent::get_admin(); // TODO: Change the autogenerated stub

    }
    //Выводим контент на странице
    public function get_kontent()
    {
        echo "Управление брендами";
        $this->get_all_brands_table();
    }
    public function get_info_table_bd(){
        $this->db_info_brands=$this->db->query("SELECT `id`,`public`,`brand_name`,`url_brands` FROM brands");
        return $this->db_info_brands;
    }
    public function approve_brands($url){
        $this->approve_br=$this->db->prepare("UPDATE `brands` SET `public`='yes' WHERE url_brands=:url");
        $this->approve_br->execute(array('url'=>$url));
    }
    public function delete_brands($url){
        $this->delete_br=$this->db->prepare("DELETE FROM `brands` WHERE url_brands=:url");
        $this->delete_br->execute(array('url'=>$url));
    }

    public function get_all_brands_table(){?>

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <input type="text" class="form-control  models-search" id="search" placeholder="Поиск записи">
                    </div>
                </div>
                <div class="col-12">
                    <form method="post">
                    <table class="table table-bordered" id="mytable">
                        <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Заголовок</th>
                            <th scope="col">Одобрена</th>
                            <th scope="col"><a class="btn btn-success" type="button" href="/Admin/Add.php?Добавить=Бренд&Option=Brand" target="_blank">Добавить+</a> </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php

                        $brands_table_db=new Brands_Admin();
                        $num_brands=1;
                        foreach ($brands_table_db->get_info_table_bd() as $db_brands_table)
                        {
            ?>
                        <tr>
                            <td >
                                <div class="custom-control custom-checkbox">
                                    <input name="<?php echo "brand".$num_brands;?>"  type="checkbox" class="custom-control-input" id="<?php echo "customCheck".$num_brands ?>" value="<?php echo $db_brands_table['url_brands']?>">
                                    <label class="custom-control-label" for="<?php echo "customCheck".$num_brands ?>"><?php echo $db_brands_table['id']?></label>
                                </div>
                            </td>
                            <td><?php echo $db_brands_table['brand_name']?></td>
                            <td><?php echo $db_brands_table['public']?></td>
                            <td><a href="<?php echo INDEX."/".$db_brands_table['url_brands']?>" class="button-delete_admin" target="_blank">Посмотреть</a></td>
                            <td><a href="/Admin/Editor.php?editor=brand&url=<?php echo $db_brands_table['url_brands']?>&Страницы=Бренда" class="button-delete_admin" target="_blank">Редактировать</a></td>
                        </tr>
            <?php
                            //одобрение поста
                            if (($_GET['class']=='Brands_Admin')&& $_POST['yes-brand']=="Одобрить"){
                                $brands_table_db->approve_brands($_POST['brand'.$num_brands]);?>
                            <script type="text/javascript">
                                setTimeout(function(){
                                    location = ''
                                },100)
                            </script>
                            <?php }
                            //Удаление
                            if (($_GET['class']=='Brands_Admin')&& $_POST['delete-brand']=="Удалить"){
                                $brands_table_db->delete_brands($_POST['brand'.$num_brands]); ?>
                                <script type="text/javascript">
                                    setTimeout(function(){
                                        location = ''
                                },100)
                            </script>
                        <?php }
                            $num_brands++;
                        } ?>

                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <button type="button" value="selectAll" class="main" onclick="checkAll()">Все</button>
            </div>
            <div class="col-lg-2">
                <button type="button" value="deselectAll" class="main" onclick="uncheckAll()">Отменить </button>
            </div>
            <div class="col-lg-8">
                <div class="dropdown">
                    <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Действие
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">

                        <a class="dropdown-item" href="?class=Brands_Admin"><input value="Одобрить" type="submit" name="yes-brand"></a>
                        <a class="dropdown-item" href="?class=Brands_Admin"><input value="Удалить" type="submit" name="delete-brand"></a>
                    </div>
                </div>
            </div>
        </div>
        </form>

    <?php }

}